sonar.projectKey=noelav07_poc-learning
sonar.organization=noelav07

sonar.projectName=poc-learning
sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=.github/**,.venv/**,venv/**,__pycache__/**

